[DEFAULT]
use_case = TON-IOT

[UNSW]
n_classes = 24
n_features = 15
weights_file = ../unsw_importance_weights.csv
f1_file = ../unsw_f1_scores.csv
unwanted_classes = ['Blipcare Blood Pressure meter', 'IPhone']
; Comment out k if not desired. k = max number of blocks (upper bound)
k = 3

[TON-IOT]
n_classes = 7
n_features = 15
weights_file = ../ton_importance_weights.csv
f1_file = ../ton_f1_scores.csv
unwanted_classes = ['mitm', 'dos', 'backdoor']
; k = 9
